AWSTemplateFormatVersion: '2010-09-09'
Description: 'Create ECR Docker Resisoty'

Parameters:
  ProjectName:
    Type: String
  EnvName:
    Type: String
  AppName:
    Type: String

Resources:
  ECR:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${ProjectName}-${EnvName}-${AppName}-ecr-registory
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: '*'
            Action: 
              - 'ecr:*'
            # Condition:
            #   ArnNotLike:
            #     aws:PrincipalArn:
            #       - !Sub arn:aws:iam::${AWS::AccountId}:role/${ProjectName}-${EnvName}-developer-role


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: Required parameters
        Parameters:
          - ProjectName
          - EnvName
          - AppName
